version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - aws ecr get-login --region us-east-1 --no-include-email
    - REPOSITORY_URI=650749741049.dkr.ecr.us-east-1.amazonaws.com/laravel-docker
    - IMAGE_TAG=6.3
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 650749741049.dkr.ecr.us-east-1.amazonaws.com/laravel-docker:6.3
#artifacts:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
